name: Release
on:
  push:
    branches:
      - hotfix

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      # check out repository code and setup node
      - uses: actions/checkout@v2

      - name: set ENV
        run: |
          echo $GITHUB_WORKSPACE
          echo ::set-env name=PROJECT_DIR::"$GITHUB_WORKSPACE"
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      # install dependencies and run semantic-release
      - run: |
          echo ::set-env name=VERSION::$(npx semantic-release@17 -p @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/github --extends $PROJECT_DIR/.github/workflows/release.config.js | grep "Created tag" | awk  '{print $8}')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}


      - uses: actions/checkout@v2
      - name: Test
        run: |
          if [[ $VERSION = "" ]]; then
              VERSION=${GITHUB_SHA:0:7}
          fi
          echo $VERSION


